// script.js – Time Log Entry App
// Author: Generated by Antigravity
// Description: Handles UI behavior, validation, and accessibility for the time‑log form.

(() => {
  // ----- DOM Elements -----
  const form = document.getElementById('time-log-form');
  const fullNameInput = document.getElementById('full-name');
  const timezoneSelect = document.getElementById('timezone');
  const hoursInput = document.getElementById('hours');
  const minutesInput = document.getElementById('minutes');
  const secondsInput = document.getElementById('seconds');
  const durationSummary = document.getElementById('duration-summary');
  const uploadZone = document.getElementById('upload-zone');
  const fileInput = document.getElementById('photo-input');
  const previewContainer = document.getElementById('preview-container');
  const previewImage = document.getElementById('preview-image');
  const removePhotoBtn = document.getElementById('remove-photo');
  const errorBannerContainer = document.createElement('div');
  const confirmationSection = document.getElementById('confirmation-section');
  const formSection = document.getElementById('form-section');
  const confName = document.getElementById('conf-name');
  const confTimezone = document.getElementById('conf-timezone');
  const confDuration = document.getElementById('conf-duration');
  const confPhoto = document.getElementById('conf-photo');
  const confTimestamp = document.getElementById('conf-timestamp');
  const submitAnotherBtn = document.getElementById('submit-another');

  // ----- Helper Functions -----
  const clamp = (value, min, max) => Math.min(Math.max(value, min), max);

  const pad = (num) => String(num).padStart(2, '0');

  const updateDurationSummary = () => {
    const h = Number(hoursInput.value) || 0;
    const m = Number(minutesInput.value) || 0;
    const s = Number(secondsInput.value) || 0;
    durationSummary.textContent = `${h}h ${m}m ${s}s`;
  };

  const showError = (message) => {
    const banner = document.createElement('div');
    banner.className = 'error-banner';
    banner.textContent = message;
    errorBannerContainer.appendChild(banner);
    // Auto‑remove after CSS animation (3.5 s). Ensure removal from DOM.
    setTimeout(() => {
      banner.remove();
    }, 3500);
  };

  const populateTimezones = () => {
    // Use Intl supported values if available; fallback to a curated subset.
    const zones = (typeof Intl !== 'undefined' && Intl.supportedValuesOf && Intl.supportedValuesOf('timeZone'))
      ? Intl.supportedValuesOf('timeZone')
      : [
        'Africa/Cairo', 'Africa/Johannesburg', 'America/New_York', 'America/Los_Angeles',
        'America/Sao_Paulo', 'Asia/Tokyo', 'Asia/Dubai', 'Asia/Kolkata',
        'Australia/Sydney', 'Europe/London', 'Europe/Paris', 'Europe/Berlin'
      ];
    zones.sort();
    zones.forEach((tz) => {
      const option = document.createElement('option');
      option.value = tz;
      option.textContent = tz;
      timezoneSelect.appendChild(option);
    });
  };

  const handleFile = (file) => {
    const validTypes = ['image/png', 'image/jpeg', 'image/webp'];
    if (!validTypes.includes(file.type)) {
      showError('Invalid file type. Only PNG, JPG, and WEBP are allowed.');
      return;
    }
    if (file.size > 10 * 1024 * 1024) {
      showError('File exceeds 10 MB size limit.');
      return;
    }
    const reader = new FileReader();
    reader.onload = (e) => {
      previewImage.src = e.target.result;
      previewContainer.hidden = false;
    };
    reader.readAsDataURL(file);
    // Store file reference for later use (confirmation display)
    previewContainer.dataset.filename = file.name;
  };

  const clearFile = () => {
    fileInput.value = '';
    previewImage.src = '';
    previewContainer.hidden = true;
    delete previewContainer.dataset.filename;
  };

  const getTimestamp = (tz) => {
    try {
      const formatter = new Intl.DateTimeFormat(undefined, {
        year: 'numeric', month: '2-digit', day: '2-digit',
        hour: '2-digit', minute: '2-digit', second: '2-digit',
        timeZone: tz,
        hour12: false,
      });
      return formatter.format(new Date());
    } catch (e) {
      // Fallback to local string if the timezone is invalid.
      return new Date().toLocaleString();
    }
  };

  // ----- Event Listeners -----
  // Clamp numeric inputs on change / input
  const clampInput = (input, min, max) => {
    let val = Number(input.value);
    if (isNaN(val)) val = min;
    val = clamp(val, min, max);
    input.value = val;
    updateDurationSummary();
  };

  hoursInput.addEventListener('input', () => clampInput(hoursInput, 0, 99));
  minutesInput.addEventListener('input', () => clampInput(minutesInput, 0, 59));
  secondsInput.addEventListener('input', () => clampInput(secondsInput, 0, 59));

  // Ensure summary updates when user manually edits values
  [hoursInput, minutesInput, secondsInput].forEach((el) => el.addEventListener('change', updateDurationSummary));

  // Upload zone click opens hidden file input
  uploadZone.addEventListener('click', () => fileInput.click());

  // Drag‑and‑drop handling
  uploadZone.addEventListener('dragover', (e) => {
    e.preventDefault();
    uploadZone.classList.add('dragover');
  });
  uploadZone.addEventListener('dragleave', () => uploadZone.classList.remove('dragover'));
  uploadZone.addEventListener('drop', (e) => {
    e.preventDefault();
    uploadZone.classList.remove('dragover');
    if (e.dataTransfer.files.length) {
      handleFile(e.dataTransfer.files[0]);
    }
  });

  // File input change (via browse)
  fileInput.addEventListener('change', () => {
    if (fileInput.files.length) handleFile(fileInput.files[0]);
  });

  // Remove photo button
  removePhotoBtn.addEventListener('click', clearFile);

  // Form submission
  form.addEventListener('submit', (e) => {
    e.preventDefault();
    // Validation
    if (!fullNameInput.value.trim()) {
      showError('Full name is required.');
      fullNameInput.focus();
      return;
    }
    if (!timezoneSelect.value) {
      showError('Timezone must be selected.');
      timezoneSelect.focus();
      return;
    }
    const h = Number(hoursInput.value) || 0;
    const m = Number(minutesInput.value) || 0;
    const s = Number(secondsInput.value) || 0;
    if (h === 0 && m === 0 && s === 0) {
      showError('Enter a duration greater than zero.');
      hoursInput.focus();
      return;
    }
    // All good – show confirmation
    confName.textContent = fullNameInput.value.trim();
    confTimezone.textContent = timezoneSelect.value;
    confDuration.textContent = `${h}h ${m}m ${s}s`;
    const attached = previewContainer.dataset.filename || 'None attached';
    confPhoto.textContent = attached;
    confTimestamp.textContent = getTimestamp(timezoneSelect.value);

    formSection.hidden = true;
    confirmationSection.hidden = false;
  });

  // Submit another – reset state
  submitAnotherBtn.addEventListener('click', () => {
    form.reset();
    clearFile();
    updateDurationSummary();
    formSection.hidden = false;
    confirmationSection.hidden = true;
    // Reset any custom UI (e.g., removed focus styles) – browsers handle this automatically.
  });

  // Initialisation
  document.body.appendChild(errorBannerContainer);
  populateTimezones();
  updateDurationSummary();
})();
